name: "rfcUpdate"

on:
  schedule:
    - cron: '0 22 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - uses: actions/checkout@v6
    - name: Setup nu
      uses: hustcer/setup-nu@v3
      with:
        version: 0.110.0
    - name: Update RFC Data
      run: nu rfc.nu
    - name: Commit and push if changed
      run: |
        git config --local user.email ${{ secrets.EMAIL }}
        git config --local user.name "KamekureMaisuke"
        git add data/rfc/rfc_index.tsv
        git diff --staged --quiet || git commit -m "update rfc_data $(date '+%Y%m%d')" && git push origin main
